### ISSUE TITLE
Improve i/o in rustc

### ISSUE THREAD

**Issue by berkus** [atilaneves/pythagoras#6]
> see "EDIT2: which means that println!("({}, {}, {})", x.clone(), y.clone(), z.clone()); reduces the total runtime by about 30%. Horrifying, but true." from [here](https://www.reddit.com/r/rust/comments/ab7hsi/comparing_pythagorean_triples_in_c_d_and_rust/ecy85jm/)

As mentioned in #5 it makes sense to exclude i/o and specifically console i/o from measurements - it's done differently in different languages runtimes and very much depend on implementation of the tty in use.

Rust has `criterion` crate to perform benchmarks properly.

**Comment by atilaneves** [comment]
I disagree, since any real usecase would involve IO of some sort.

**Comment by berkus** [comment]
But you cannot use it in measuring because of different implementations of such io. Even between linux and osx kernel the console i/o is implemented differently.

Please relabel your benchmarks as I/O benchmarks then, as this is what they are.

**Comment by atilaneves** [comment]
> But you cannot use it in measuring

I can. I did.

>  because of different implementations of such io

I know. That was on purpose.

> Please relabel your benchmarks as I/O benchmarks then, as this is what they are.

Nope.
