### ISSUE TITLE
Consider using -C opt-level=3 for Rust

### ISSUE THREAD

**Issue by lnicola** [atilaneves/pythagoras#7]
The default optimization level for release builds [is 3, not 2](https://doc.rust-lang.org/book/ch14-01-release-profiles.html). I'm not saying it makes a difference here, but it seems fair to use that.

**Comment by atilaneves** [comment]
Then I'd have to change it to `-O3` for clang and ldc as well. I think I tried on ldc once and it didn't make a difference. I'd also have to redo eveything...
